### ISSUE TITLE
Mitigate "Leaky Vessels" - upgrade packages

### ISSUE THREAD

**Issue by pluhmen** [docker/packaging#192]
Docker packages provided should be updated according to your very own advisory:

https://www.docker.com/blog/docker-security-advisory-multiple-vulnerabilities-in-runc-buildkit-and-moby/

> If you are using affected versions of runc, BuildKit, Moby, or Docker Desktop, make sure to update to the latest versions as soon as patched versions become available (all to be released no later than February 1 and linked in the following table)

Also GitHub Action Runners are affected by this:

**Workflow file**
```
name: Docker runtime info

on:
  workflow_dispatch:

jobs:
  docker_info:
    runs-on: ubuntu-latest
    steps:
      - name: docker info
        run: |
          docker info

  runc_version:
    runs-on: ubuntu-latest
    steps:
      - name: runc version
        run: |
          runc --version
```
**Output**
```
 docker info
  shell: /usr/bin/bash -e {0}
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
```
```
  runc --version
  shell: /usr/bin/bash -e {0}
runc version 1.1.12
commit: v1.1.12-0-g51d5e94
spec: 1.0.2-dev
go: go1.20.13
libseccomp: 2.5.3
```
